### ISSUE TITLE
Code line indicators are off in the examples in '2.6 Defining the class SBEGame'

### ISSUE THREAD

**Issue by Pascal-H** [codeZeilen/SqueakByExample-english#17]
In section '2.6 Defining the class SBEGame' and following, the line enumeration seems to be off and the categorization-connotation is not separated from the source code to be inserted in the System 
Browser:
E.g. in `Method 2.4: Initializing the game`, line with the number 1 is as follows:
```
1 SBEGame'»'initialization
2 initialize
3    | height overallBorderWidth sampleCell width |
      ...
```
This confused me a bit, because I got tons of complaints for undefined variables etc. and could not autocategorize the `initialize` method, because it was called `SBEGame'»'initialization`.

This might be a side effect of [my half-broken make process](https://github.com/codeZeilen/SqueakByExample-english/issues/16#issuecomment-548026470), but also in the completely compiled older version, it is even more misleading because there the name `initialize` is not written plainly at all:
```
SBEGame»initialize
    | height overallBorderWidth sampleCell width |
    ...
```

**Comment by codeZeilen** [comment]
:D This even confused me a bit. 

@LinqLover Might this be a result of the new shell script?

The second listing is actually correct. This is the way we denote that this is the method initialize in the class SBEGame (In the image you can even write SBEGame>>#initialize and will get the corresponding CompiledMethod object)

**Comment by codeZeilen** [comment]
Hm... Not sure whether this fixes the right problem. The first line of the
file also has to be removed. Does the commit fix that?

Christoph Thiede <notifications@github.com> schrieb am Di., 5. Nov. 2019,
18:09:

**Comment by LinqLover** [comment]
Ah, that was a conceptual error. I just read "class name, some `>`s, selector" and directly thought about Smalltalks `#>>` selector ... Will fix this.

**Comment by LinqLover** [comment]
Okay, what methods are you concretely referring to? Methods in chapter 2 appear to be presented correctly to me in the [latest build](https://drive.google.com/file/d/1JND416mbf-zEHH9ojUt4IGzI5YSQH9GS/view).

- Method 1.1 (`testShout`) is not yet in SmalltalkSources, should we add it?

- Method 1.2 (`shout`) is displayed without category due to a bug in the script (but it's not a regression 😜). Will fix that.

**Comment by codeZeilen** [comment]
For example Method 2.2. The first line is not the method signature but a
combination of the class name and the method category. The classname should
have been added to the "initialize" on the second line (they look very
similar...).
In the end, the category should not be in the listings at all, and the
method name should be CLASSNAME>>METHODNAME

Am Di., 5. Nov. 2019 um 19:57 Uhr schrieb Christoph Thiede <
notifications@github.com>:

**Comment by LinqLover** [comment]
Thank you for the explanation, I was barking up the wrong tree. 8c3bd51ff043a786b03db1ac6c7d90f14d99e8af should finally fix it, is that okay?

**Comment by codeZeilen** [comment]
Looks good to me :)
